---
name: Test
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v30
      - name: Build the nix shell
        run: nix develop --command just --version
      - uses: Swatinem/rust-cache@v2

      # setup databases
      - name: Start databases
        run: nix develop --command just dbs/start

      # run tests
      - name: Run tests
        run: nix develop --command just test
